version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Globber
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: appairbnbpro-db
    restart: always
    environment:
      MYSQL_DATABASE: appairbnbpro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: