[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
target = "production"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 80 